import json
import os
import re
import textwrap
from pathlib import PurePosixPath

from conan import ConanFile
from conan.tools.build import check_min_cppstd
from conan.tools.cmake import CMake, CMakeDeps, CMakeToolchain, cmake_layout
from conan.tools.files import (
    apply_conandata_patches,
    collect_libs,
    copy,
    export_conandata_patches,
    get,
    rm,
    rmdir,
    save,
    load,
)
from conan.tools.scm import Version

required_conan_version = ">=1.53.0"


def components_from_dotfile(dotfile):
    """
    Parse the dotfile generated by the
    [cmake --graphviz](https://cmake.org/cmake/help/latest/module/CMakeGraphVizOptions.html)
    option to generate the list of available Clang CMake targets and their inter-component dependencies.
    """

    def node_labels(dot):
        """
        match each node in the dotfile with a label property, and map the label to a conan component
        """
        label_replacements = {
            "LibXml2::LibXml2": "libxml2::libxml2",
            "ZLIB::ZLIB": "zlib::zlib",
            "zstd::libzstd_static": "zstd::zstdlib",
            "-lpthread": "pthread",
        }
        for row in dot:
            match_label = re.match(
                r"""^\s*"(node[0-9]+)"\s*\[\s*label\s*=\s*"(.+)".*""", row
            )
            if match_label:
                node = match_label.group(1)
                label = match_label.group(2)
                yield node, label_replacements.get(label, label)

    def node_dependencies(dot):
        """
        Using the nodes with labels, extract the component dependencies of each node
        """
        ignore_deps = []
        labels = {k: v for k, v in node_labels(dot)}
        for row in dot:
            match_dep = re.match(r"""^\s*"(node[0-9]+)"\s*->\s*"(node[0-9]+)".*""", row)
            if match_dep:
                node_label = labels[match_dep.group(1)]
                dependency = labels[match_dep.group(2)]
                if (
                    node_label.startswith("clang")
                    and not node_label.startswith("clang-")
                    and PurePosixPath(dependency).parts[-1] not in ignore_deps
                ):
                    yield node_label, labels[match_dep.group(2)]
        # some components don't have dependencies
        for label in labels.values():
            if label.startswith("clang"):
                yield label, None

    system_libs = {
        "dl",
        "version",
    }
    components = {}
    dotfile_rows = dotfile.split("\n")
    for node, dependency in node_dependencies(dotfile_rows):
        key = "system_libs" if dependency in system_libs else "requires"
        if node not in components:
            components[node] = {"system_libs": [], "requires": []}
            if dependency is not None:
                components[node][key] = [
                    f"llvm-core::{dependency}"
                    if dependency.startswith("LLVM")
                    else dependency
                ]
        elif dependency is not None:
            components[node][key].append(
                f"llvm-core::{dependency}"
                if dependency.startswith("LLVM")
                else dependency
            )

    return components


class LLVMClangConan(ConanFile):
    name = "llvm-clang"
    description = "Clang is a compiler front-end for the C family of languages (C, C++ and Objective-C)"
    license = "Apache-2.0 WITH LLVM-exception"
    url = "https://github.com/conan-io/conan-center-index"
    homepage = "https://github.com/llvm/llvm-project/blob/main/clang"
    topics = ("llvm", "clang")

    package_type = "library"
    settings = "os", "arch", "compiler", "build_type"
    options = {
        "shared": [True, False],
        "fPIC": [True, False],
        "with_xml2": [True, False],
    }
    default_options = {
        "shared": False,
        "fPIC": True,
        "with_xml2": True,
    }

    @property
    def _version_major(self):
        return Version(self.version).major

    def export_sources(self):
        export_conandata_patches(self)

    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC

    def configure(self):
        if self.options.shared:
            self.options.rm_safe("fPIC")

    def requirements(self):
        self.requires(f"llvm-core/{self.version}")
        if self.options.with_xml2:
            self.requires("libxml2/[>=2.12.5 <3]")

    def layout(self):
        cmake_layout(self, src_folder="src")

    def validate(self):
        if self.settings.compiler.cppstd:
            check_min_cppstd(self, 17)

    def build_requirements(self):
        self.tool_requires("cmake/[>=3.20 <5]")

    def source(self):
        get(self, **self.conan_data["sources"][self.version]["clang"], strip_root=True)
        get(
            self,
            **self.conan_data["sources"][self.version]["cmake"],
            strip_root=True,
            destination=os.path.join(self.export_sources_folder, "cmake"),
        )

    def generate(self):
        deps = CMakeDeps(self)
        deps.generate()

        tc = CMakeToolchain(self)
        tc.cache_variables["CLANG_BUILT_STANDALONE"] = True
        tc.cache_variables["LLVM_INCLUDE_TESTS"] = False
        tc.cache_variables["CLANG_ENABLE_LIBXML2"] = (
            "FORCE_ON" if self.options.with_xml2 else False
        )
        tc.generate()

    @property
    def _graphviz_file(self):
        return os.path.join(self.build_folder, "llvm-clang.dot")

    def build(self):
        apply_conandata_patches(self)
        cmake = CMake(self)
        graphviz_args = [f"--graphviz={self._graphviz_file}"]
        exclude_patterns = [
            "CONAN_LIB.*",
        ]
        graphviz_options = textwrap.dedent(f"""
                   set(GRAPHVIZ_EXECUTABLES OFF)
                   set(GRAPHVIZ_MODULE_LIBS OFF)
                   set(GRAPHVIZ_OBJECT_LIBS OFF)
                   set(GRAPHVIZ_IGNORE_TARGETS "{';'.join(exclude_patterns)}")
               """)
        save(
            self,
            os.path.join(self.build_folder, "CMakeGraphVizOptions.cmake"),
            graphviz_options,
        )
        cmake.configure(cli_args=graphviz_args)
        cmake.build()

    @property
    def _module_variables_file_rel_path(self):
        return os.path.join(
            "lib", "cmake", "clang", f"conan-official-{self.name}-variables.cmake"
        )

    def _create_cmake_module_variables(self, module_file):
        content = textwrap.dedent("""\
                set(CLANG_CMAKE_DIR "${CMAKE_CURRENT_LIST_DIR}")
                list(APPEND CMAKE_MODULE_DIR ${CMAKE_CURRENT_LIST_DIR})
                if(NOT TARGET clang-tablegen-targets)
                  add_custom_target(clang-tablegen-targets)
                endif()
               """)
        save(self, module_file, content)

    @property
    def _build_info_file(self):
        return os.path.join(
            self.package_folder, "lib", "cmake", "clang", "clang-build-info.json"
        )

    @property
    def _build_info(self):
        components = components_from_dotfile(load(self, self._graphviz_file))
        return {
            "components": components,
        }

    def _write_build_info(self):
        build_info = self._build_info
        with open(self._build_info_file, "w", encoding="utf-8") as fp:
            json.dump(build_info, fp, indent=2)

        return build_info

    def _read_build_info(self) -> dict:
        with open(self._build_info_file, encoding="utf-8") as fp:
            return json.load(fp)

    def package(self):
        copy(
            self,
            "LICENSE.txt",
            src=self.source_folder,
            dst=os.path.join(self.package_folder, "licenses"),
        )
        cmake = CMake(self)
        cmake.install()

        cmake_folder = os.path.join(self.package_folder, "lib", "cmake", "clang")
        rm(self, "ClangConfig.cmake", cmake_folder)
        rmdir(self, os.path.join(self.package_folder, "share"))
        if self.options.shared:
            rm(self, "*.a", os.path.join(self.package_folder, "lib"))

        self._write_build_info()
        self._create_cmake_module_variables(
            os.path.join(self.package_folder, self._module_variables_file_rel_path)
        )

    def package_info(self):
        self.cpp_info.set_property("cmake_file_name", "Clang")
        self.cpp_info.set_property(
            "cmake_build_modules", [self._module_variables_file_rel_path]
        )
        self.cpp_info.builddirs.append(os.path.join("lib", "cmake", "clang"))
        if self.options.with_xml2:
            self.cpp_info.requires.append("libxml2::libxml2")

        if not self.options.shared:
            build_info = self._read_build_info()
            components = build_info["components"]
            for component_name, data in components.items():
                self.cpp_info.components[component_name].set_property(
                    "cmake_target_name", component_name
                )
                self.cpp_info.components[component_name].libs = [component_name]
                self.cpp_info.components[component_name].requires = data["requires"]
                self.cpp_info.components[component_name].system_libs = data[
                    "system_libs"
                ]
        else:
            self.cpp_info.set_property("cmake_target_name", "Clang")
            self.cpp_info.libs = collect_libs(self)
